#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2026 LiuFudi
#
# This file is part of fn-fancontrol, licensed under the GNU General Public
# License version 3 or (at your option) any later version.
# See the LICENSE file for the full text.
"""Compile the donation QR images into a JavaScript module.

The packaged application deliberately carries no stand-alone copy of the QR
codes.  A file under ``app/ui/images/`` can be replaced inside the .fpk -- or
in an already installed copy of the app -- without touching a line of code;
inlining them as data URIs makes that a source change followed by a rebuild.

The originals live in ``assets/donate/`` so they are kept in the repository
but are never part of the packaged tree.  The generated module is committed,
so a plain checkout builds without running this script first.

Usage:  python3 tools/make_donate_qr.py [repo-root]
"""

from __future__ import annotations

import base64
import json
import os
import sys

#: donation key used by donate.json -> file name under assets/donate/
IMAGES = {"wechat": "wechat.png", "alipay": "alipay.png"}

ASSET_DIR = os.path.join("assets", "donate")
OUTPUT = os.path.join("package", "app", "ui", "donate-qr.js")

MIME = {
    ".png": "image/png",
    ".jpg": "image/jpeg",
    ".jpeg": "image/jpeg",
    ".gif": "image/gif",
    ".webp": "image/webp",
}

HEADER = """\
/* SPDX-License-Identifier: GPL-3.0-or-later
 * Copyright (C) 2026 LiuFudi
 *
 * This file is part of fn-fancontrol, licensed under the GNU General Public
 * License version 3 or (at your option) any later version.
 * See the LICENSE file for the full text.
 *
 * GENERATED by tools/make_donate_qr.py -- do not edit by hand.
 * Donation QR codes, inlined as data URIs so the packaged application contains
 * them as data rather than as separate image files. */
"""


def mime_for(path):
    return MIME.get(os.path.splitext(path)[1].lower(), "application/octet-stream")


def build(root):
    """Return the module text, or raise ``OSError`` naming the missing file."""
    entries = []
    for key in sorted(IMAGES):
        path = os.path.join(root, ASSET_DIR, IMAGES[key])
        if not os.path.isfile(path):
            raise OSError("missing %s" % os.path.relpath(path, root))
        with open(path, "rb") as handle:
            blob = handle.read()
        encoded = base64.b64encode(blob).decode("ascii")
        entries.append((key, "data:%s;base64,%s" % (mime_for(path), encoded)))

    chunks = [HEADER, "window.FANCONTROL_DONATE_QR = {\n"]
    for position, (key, uri) in enumerate(entries):
        comma = "," if position + 1 < len(entries) else ""
        chunks.append("  %s: %s%s\n" % (json.dumps(key), json.dumps(uri), comma))
    chunks.append("};\n")
    return "".join(chunks)


def main(argv):
    if len(argv) > 1:
        root = os.path.abspath(argv[1])
    else:
        root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

    try:
        text = build(root)
    except OSError as exc:
        sys.stderr.write("make_donate_qr: %s\n" % exc)
        return 1

    target = os.path.join(root, OUTPUT)
    try:
        with open(target, "r", encoding="utf-8") as handle:
            if handle.read() == text:
                print("make_donate_qr: %s already up to date" % OUTPUT)
                return 0
    except OSError:
        pass

    os.makedirs(os.path.dirname(target), exist_ok=True)
    with open(target, "w", encoding="utf-8") as handle:
        handle.write(text)
    print("make_donate_qr: wrote %s (%d bytes)" % (OUTPUT, len(text)))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
